### ISSUE TITLE
embeddable statistics

### ISSUE THREAD

**Issue by amgando** [NEAR-Edu/stats.gallery#10]
we should think carefully about how to break up these stats into shareable components with their own access point.  consider that others may want to use these statistics as widgets in their own applications, for example, or on their vanity sites.

something like this might help, not sure though
https://github.com/karol-f/vue-custom-element
https://itnext.io/vuidget-how-to-create-an-embeddable-vue-js-widget-with-vue-custom-element-674bdcb96b97

**Comment by encody** [comment]
@amgando Are we looking at something like [Spotify embeds](https://developer.spotify.com/documentation/widgets/generate/embed/)? Those are embedded using iframes, which have the advantage of only having to write one tag in one place instead of three tags in three places. Or is the intent with embeddable statistics different?

**Comment by amgando** [comment]
@encody I hadn't really done much research on options here. I think the goal would be to offer up a modern embed experience to devs as well as low / no tech folks who want to add widgets to Wordpress, Wix, etc.

not sure what the level of effort on any of this would be so it's a research problem at this point afaik

**Comment by encody** [comment]
@amgando I'll put together something using iframes and we'll see if that looks appropriate.
